[package]
name = "mdv-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "0.8.0"
serde = { version = "1.0.165", features = ["derive"] }
thiserror = "1.0.40"
log = "0.4.19"

[dependencies.mdv-math]
path = "../mdv-math"
